apiVersion: v1
kind: ConfigMap

metadata:
  name: go-jobs-config
  namespace: go-jobs

data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: go_jobs_db

  REDIS_HOST: redis-service
  REDIS_PORT: "6379"