apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: go-jobs

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
      - name: worker

        image: go-jobs-main-worker:latest
        imagePullPolicy: Never

        env:
        - name: DB_DSN
          value: "host=postgres-service user=postgres password=ankush123 dbname=go_jobs_db port=5432 sslmode=disable"

        - name: REDIS_ADDR
          value: "redis-service:6379"